CREATE TABLE IF NOT EXISTS usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    dni VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    sexo ENUM('Masculino', 'Femenino') NOT NULL,
    nivel VARCHAR(50) NOT NULL,
    nivel_anterior VARCHAR(50) DEFAULT NULL,
    fecha_recategorizacion DATE DEFAULT NULL,
    telefono VARCHAR(20),
    tel_alternativo VARCHAR(20),
    fecha_nacimiento DATE,
    pais VARCHAR(50) DEFAULT 'Argentina',
    provincia VARCHAR(50),
    localidad VARCHAR(50),
    instagram VARCHAR(100),
    facebook VARCHAR(100),
    x VARCHAR(100),
    brazo_habil ENUM('Derecho', 'Izquierdo') NOT NULL,
    posicion ENUM('Lado Derecho de la Cancha', 'Lado Izquierdo de la Cancha', 'Indistinto') NOT NULL,
    rol ENUM('admin', 'user') DEFAULT 'user',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
